name: Build and deploy Python app to Azure Web App - Pneumonia

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLASK_ENV: production
  WEBSITE_WEBDEPLOY_USE_SCM: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create static directory
      run: mkdir -p static
        
    - name: Zip package
      run: zip -r release.zip . -x '*.git*' '*.github*' 'venv/*'
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4  # Changed from v3 to v4
      with:
        name: python-app
        path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4  # Changed from v3 to v4
      with:
        name: python-app
        
    - name: Unzip package
      run: unzip release.zip
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Pneumonia'
        package: release.zip
        runtime: 'PYTHON|3.10'  # Explicit runtime specification
